name: hscpy
dependencies:
  - matplotlib
  - python=3.11
  - numpy>=1.25
  - pandas>=1.5
  - pip
  - jupyter
  - black[jupyter]
  - ipykernel
  - seaborn
  - scipy
  - pip:
    - git+https://github.com/fraterenz/futils@v0.0.2
    - git+https://github.com/fraterenz/hscpy@v0.4.3

